### ISSUE TITLE
Pisah CSS footer dan header

### ISSUE THREAD

**Issue by NaMLiM** [NaMLiM/pindad-clone#2]
Mungkin style CSS header sama footer dipisah?

**Comment by kanam129** [comment]
knapa dipisah??

**Comment by NaMLiM** [comment]
Kan contentnya nanti di include pake php...

Apa tetep aja?

**Comment by kanam129** [comment]
ohhh mksdnya footer sama header digabung 1 file. tak kira dipisah file header sama footernya

**Comment by NaMLiM** [comment]
> ohhh mksdnya footer sama header digabung 1 file. tak kira dipisah file header sama footernya

iya...

**Comment by NaMLiM** [comment]
Done #3
